{{ if .Values.recycle.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "uptime-kuma.fullname" . }}-recycle
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - delete
{{ end }}
---
