{{ if .Values.recycle.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "uptime-kuma.fullname" . }}-recycle
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: recycle
subjects:
- kind: ServiceAccount
  name: {{ include "uptime-kuma.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}