apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime
  labels:
    app: uptime
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: uptime
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: uptime
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      containers:
      - args:
        - server/server.js
        command:
        - node
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "2000"
        name: uptime
        image: "{{ .Values.image.repository }}/uptime:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{ - with .Values.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        volumeMounts:
        - mountPath: /app/data
          name: storage
        ports:
          - name: http
            containerPort: 3001
            protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 3001
        readinessProbe:
          tcpSocket:
            port: 3001
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: uptime