apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: uptime
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: uptime