apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: uptime-kuma
  name: uptime
  namespace: uptime-kuma
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: freenas-iscsi-csi