name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build backend
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --pull \
            --cache-from supporttools/uptime-kuma:latest \
            -t supporttools/uptime-kuma:"v${{ github.run_number }}" \
            -t supporttools/uptime-kuma:latest \
            --push \
            -f Dockerfile .

  Publish:
    runs-on: ubuntu-latest
    needs:
      - Build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Helm Lint
        run: helm lint charts/uptime-kuma/

      - name: Package Helm chart
        run: |
          export CHART_VERSION="v${{ github.run_number }}"
          export APP_VERSION="v${{ github.run_number }}"
          export IMAGE_TAG="v${{ github.run_number }}"
          echo "CHART_VERSION=${CHART_VERSION}"
          echo "APP_VERSION=${APP_VERSION}"
          echo "IMAGE_TAG=${IMAGE_TAG}"
          envsubst < charts/uptime-kuma/Chart.yaml.template > charts/uptime-kuma/Chart.yaml
          envsubst < charts/uptime-kuma/values.yaml.template > charts/uptime-kuma/values.yaml
          helm package charts/uptime-kuma --destination helm/repo

      - name: Checkout helm-chart repository
        uses: actions/checkout@v4
        with:
          repository: supporttools/helm-chart
          path: helm-chart
          token: ${{ secrets.BOT_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"

      - name: Update Helm repository
        run: |
          cp helm/repo/uptime-kuma-*.tgz helm-chart/
          cd helm-chart
          helm repo index . --url https://charts.support.tools
          git add .
          git commit -m "Update Helm chart for uptime-kuma"
          git push